name: navisight
description: A Flutter application that assists visually impaired users with indoor navigation through AI-powered image analysis and voice interactions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  http: ^1.4.0
  path_provider: ^2.0.11
  path: ^1.8.2
  provider: ^6.0.3
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true